-- models.lua - Model Registry and Configuration
-- Defines all AI model configurations and their parameters

local Models = {
	flash = {
		name = "ChatMind 1 Flash",
		tag = "FLASH",
		saveFile = "cm1flash.json",
		maxTokens = 20,
		markovOrder = 1,
		bayesSmoothing = 1.0,
		maxLog = 500,
		maxChatSessions = 20,
		color = Color3.fromRGB(255, 200, 40),
		confidenceThreshold = 0.35,
		coherenceThreshold = 0.40,
		perplexityLimit = 8.0,
		minMarkovKeys = 15,
		fallbackToPool = true,
		contextLimit = 8192,
		effectiveParams = 32768,
		effectiveParamsMin = 4096,
		effectiveParamsMax = 131072,
		memorySlots = 8,
		learningRate = 0.05,
		topKSampling = 40,
		nucleusSampling = 0.9,
		modes = {
			spark = {
				label = "Spark", icon = "⚡",
				color = Color3.fromRGB(255, 210, 50),
				candidates = 1, delayMin = 0.05, delayMax = 0.10,
				tokenCap = 10, rescore = false, rescorePasses = 0,
				diversityWeight = 0.2, coherenceWeight = 0.8,
				temperature = 0.9, repetitionPenalty = 0.3,
			},
			sparking_thinking = {
				label = "Sparking Thinking", icon = "⚡🧠",
				color = Color3.fromRGB(160, 80, 255),
				candidates = 5, delayMin = 0.25, delayMax = 0.45,
				tokenCap = 20, rescore = true, rescorePasses = 1,
				diversityWeight = 0.4, coherenceWeight = 1.2,
				temperature = 0.75, repetitionPenalty = 0.5,
			},
			think = {
				label = "Think", icon = "🧠",
				color = Color3.fromRGB(80, 160, 255),
				candidates = 8, delayMin = 1.1, delayMax = 1.7,
				tokenCap = 999, rescore = true, rescorePasses = 3,
				diversityWeight = 0.6, coherenceWeight = 1.8,
				temperature = 0.6, repetitionPenalty = 0.7,
			},
		},
		defaultMode = "sparking_thinking",
	},

	deepthink = {
		name = "ChatMind 1 DeepThink",
		tag = "DEEP",
		saveFile = "cm1deepthink.json",
		maxTokens = 999,
		markovOrder = 2,
		bayesSmoothing = 0.3,
		maxLog = 2000,
		maxChatSessions = 20,
		color = Color3.fromRGB(100, 80, 255),
		confidenceThreshold = 0.25,
		coherenceThreshold = 0.55,
		perplexityLimit = 6.0,
		minMarkovKeys = 30,
		fallbackToPool = true,
		contextLimit = 32768,
		effectiveParams = 131072,
		effectiveParamsMin = 16384,
		effectiveParamsMax = 524288,
		memorySlots = 20,
		learningRate = 0.03,
		topKSampling = 60,
		nucleusSampling = 0.95,
		modes = {
			deepthink = {
				label = "DeepThink", icon = "🔮",
				color = Color3.fromRGB(130, 90, 255),
				candidates = 12, delayMin = 2.0, delayMax = 3.5,
				tokenCap = 999, rescore = true, rescorePasses = 5,
				diversityWeight = 1.0, coherenceWeight = 2.5,
				useAllExperts = true, bigramBoost = true, trigramBoost = true,
				sentimentCheck = true, temperature = 0.5, repetitionPenalty = 0.9,
			},
			extended_dt = {
				label = "Extended DT", icon = "🔮✨",
				color = Color3.fromRGB(180, 100, 255),
				candidates = 15, delayMin = 4.0, delayMax = 6.0,
				tokenCap = 999, rescore = true, rescorePasses = 8,
				diversityWeight = 1.2, coherenceWeight = 3.0,
				useAllExperts = true, bigramBoost = true, trigramBoost = true,
				sentimentCheck = true, temperature = 0.4, repetitionPenalty = 1.0,
			},
		},
		defaultMode = "deepthink",
	},

	pro = {
		name = "ChatMind 1 Pro",
		tag = "PRO",
		saveFile = "cm1pro.json",
		maxTokens = 999,
		markovOrder = 2,
		bayesSmoothing = 0.5,
		maxLog = 3000,
		maxChatSessions = 20,
		color = Color3.fromRGB(50, 200, 255),
		confidenceThreshold = 0.30,
		coherenceThreshold = 0.50,
		perplexityLimit = 7.0,
		minMarkovKeys = 20,
		fallbackToPool = true,
		contextLimit = 65536,
		effectiveParams = 262144,
		effectiveParamsMin = 32768,
		effectiveParamsMax = 1048576,
		memorySlots = 30,
		learningRate = 0.04,
		topKSampling = 80,
		nucleusSampling = 0.97,
		webEnabled = false,
		modes = {
			lightning = {
				label = "Lightning Fusion", icon = "⚡💎",
				color = Color3.fromRGB(50, 210, 255),
				candidates = 8, delayMin = 0.1, delayMax = 0.3,
				tokenCap = 30, rescore = true, rescorePasses = 2,
				diversityWeight = 0.5, coherenceWeight = 1.5,
				bigramBoost = true, trigramBoost = true,
				temperature = 0.7, repetitionPenalty = 0.6,
				fusionMode = true,
			},
			thinking = {
				label = "Thinking", icon = "💎🧠",
				color = Color3.fromRGB(30, 170, 255),
				candidates = 12, delayMin = 1.5, delayMax = 2.5,
				tokenCap = 999, rescore = true, rescorePasses = 4,
				diversityWeight = 0.8, coherenceWeight = 2.0,
				bigramBoost = true, trigramBoost = true,
				useAllExperts = true, sentimentCheck = true,
				temperature = 0.55, repetitionPenalty = 0.8,
				fusionMode = true, useWeb = true,
			},
			extended = {
				label = "Extended Thinking", icon = "💎🔮",
				color = Color3.fromRGB(20, 140, 255),
				candidates = 18, delayMin = 3.5, delayMax = 5.0,
				tokenCap = 999, rescore = true, rescorePasses = 7,
				diversityWeight = 1.0, coherenceWeight = 2.8,
				bigramBoost = true, trigramBoost = true,
				useAllExperts = true, sentimentCheck = true,
				temperature = 0.45, repetitionPenalty = 0.95,
				fusionMode = true, useWeb = true,
			},
		},
		defaultMode = "lightning",
	},
}

return Models
